POST http://localhost:5001/users
Content-Type: application/json

{
    "name": "ryan",
    "email" : "@gmail.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "admin"
}

###
//get all user

GET http://localhost:5001/users

###
//get all karyawan

GET http://localhost:5001/allkaryawan

###
//get single user

GET http://localhost:5001/users/183a96f2-4629-44f3-b7ff-4d1c5e7996e4/

###
//Update User

PATCH  http://localhost:5001/users183a96f2-4629-44f3-b7ff-4d1c5e7996e4
Content-Type: application/json

{
    "name": "John update",
    "email" : "john@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "karyawan"
}

###
//Delete User
DELETE  http://localhost:5001/users183a96f2-4629-44f3-b7ff-4d1c5e7996e4


###
//Login User
POST http://localhost:5001/login
Content-Type: application/json

{

    "email" : "john@gmail.com",
    "password": "112233"

}

###
//Login Admin
POST http://localhost:5001/login
Content-Type: application/json

{

    "email" : "admin@gmail.com",
    "password": "112233"

}

###
//Get All Servis
GET http://localhost:5001/servis

###
//Get ongoing Servis (staff)
GET http://localhost:5001/ongoingservis

###
//Get ongoing Servis (cust)
GET http://localhost:5001/ongoingserviscust

###
//Me (Session)
GET http://localhost:5001/me

###
//Logout
DELETE http://localhost:5001/Logout

###
//get all product

GET http://localhost:5001/products

###
//Buat produk
POST http://localhost:5001/products
Content-Type: application/json

{
    "name": "produk admin",
    "price": 1234
}

###
//get single product

GET http://localhost:5001/products/4a0113da-abf8-45d9-8f39-387355770fc9


###
//Updet Prduk
PATCH http://localhost:5001/products/1ec2f614-746d-4ef7-9be5-56d231027a7c
Content-Type: application/json

{
    "name": "produk ueeeed",
    "price": 123
}



###
//delete Prduk
DELETE http://localhost:5001/products/4a0113da-abf8-45d9-8f39-387355770fc9


